FROM node:alpine
ENV TZ=America/Sao_Paulo

WORKDIR /app

RUN apk update && apk upgrade

RUN apk add -U tzdata
RUN cp /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime

COPY ./frontend/package.json .

RUN npm install

COPY ./frontend/ .

RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start"]