FROM node:alpine
ENV TZ=America/Sao_Paulo
ENV NODE_OPTIONS="--trace-deprecation"

WORKDIR /app

RUN apk update && apk upgrade

RUN apk add -U tzdata
RUN cp /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime

COPY ./frontend/package.json .

RUN npm install --force --legacy-peer-deps

COPY ./frontend/ .

RUN rm ./.env
COPY ./frontend/.env.prod ./.env

RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start"]