services:
  backend:
    build:
      context: ./
      dockerfile: docker/backend/remote/Dockerfile.Production
    restart: always
    privileged: true
    volumes:
      - ./configs/nginx_backend/nginx.conf:/etc/nginx/nginx.conf
      - ./configs/nginx_backend/conf.d:/etc/nginx/conf.d
    ports:
      - "6001:6001"
      - "9000:9001"
    networks:
      - curriculus-net
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "100m"

  frontend:
    build:
      context: ./
      dockerfile: docker/frontend/Dockerfile.Production
    depends_on:
      - backend
    restart: always
    ports:
      - "3000:3000"
    networks:
      - curriculus-net
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "100m"

networks:
  curriculus-net:
    name: curriculus-net
    driver: bridge
