namespace NodeJS {
  export interface ProcessEnv {
    NEXT_PUBLIC_APP_ENV: string;
    NEXTAUTH_URL: string;
    NEXT_PUBLIC_NEXTAUTH_SECRET: string;
    NEXT_PUBLIC_API_BACKEND_BASE_URL: string;
    NEXT_PUBLIC_API_BACKEND_REGISTER: string;
    NEXT_PUBLIC_PUSHER_APP_ID: string;
    NEXT_PUBLIC_PUSHER_APP_KEY: string;
    NEXT_PUBLIC_PUSHER_APP_SECRET: string;
    NEXT_PUBLIC_PUSHER_HOST: string;
    NEXT_PUBLIC_PUSHER_PORT: number;
    NEXT_PUBLIC_PUSHER_SCHEME: string;
    NEXT_PUBLIC_PUSHER_APP_CLUSTER: string;
    NEXT_PUBLIC_PUSHER_LOG_CONSOLE: boolean;
    NEXT_PUBLIC_PUSHER_LOG_CONNECTION: boolean;
    NEXT_PUBLIC_ROBOT_DOWNLOADER: string;
    NEXT_PUBLIC_VERSION: string;
    NEXT_PUBLIC_APP_NAME: string;
    NEXT_PUBLIC_GROUP_NAME_ADMIN: string;
    NEXT_PUBLIC_GROUP_NAME_RPA: string;
  }
}
